export const ACTION_MODES = {
    REPLACE_DATA: 'REPLACE_DATA',
    APPEND_DATA: 'APPEND_DATA',
    PREPEND_DATA: 'PREPEND_DATA',
};

export const ACTIONS = {
    FETCH_HOME_CONFIG: 'FETCH_HOME_CONFIG',
    UPDATE_HOME_CONFIG: 'UPDATE_HOME_CONFIG',
};

export const MUTATIONS = {
    SET_HOME_CONFIG: 'SET_HOME_CONFIG',
    SET_HOME_ACTIONS: 'SET_HOME_ACTIONS',
};
