export const ACTION_MODES = {
    REPLACE_DATA: 'REPLACE_DATA',
    APPEND_DATA: 'APPEND_DATA',
    PREPEND_DATA: 'PREPEND_DATA',
};

export const ACTIONS = {
    FETCH_SETTINGS: 'FETCH_SETTINGS',

    FETCH_HOME_ACTIONS: 'FETCH_HOME_ACTIONS',
    UPDATE_HOME_CONFIG: 'UPDATE_HOME_CONFIG',

    FETCH_NOTES: 'FETCH_NOTES',
    SAVE_NOTE: 'SAVE_NOTE',
    DUPLICATE_NOTE: 'DUPLICATE_NOTE',
    RENAME_NOTE: 'RENAME_NOTE',
    REMOVE_NOTE: 'REMOVE_NOTE',

    START_MEDIA_SERVER: 'START_MEDIA_SERVER',
    CLOSE_MEDIA_SERVER: 'CLOSE_MEDIA_SERVER',
    WAIT_MEDIA_CONFIGURE: 'WAIT_MEDIA_CONFIGURE',
};

export const MUTATIONS = {
    SET_SETTINGS: 'SET_SETTINGS',
    SET_HOME_ACTIONS: 'SET_HOME_ACTIONS',

    SET_NOTES: 'SET_NOTES',
    ADD_NOTE: 'ADD_NOTE',
    SET_NOTE_NAME: 'SET_NOTE_NAME',
    DELETE_NOTE: 'DELETE_NOTE',

    SET_MEDIA_SERVER_ADDRESS: 'SET_MEDIA_SERVER_ADDRESS',
    SET_MEDIA_AS_CONFIGURED: 'SET_MEDIA_AS_CONFIGURED',
};
